### ISSUE TITLE
have_published_event matcher.

### ISSUE THREAD

**Issue by andrasio** [palkan/active_event_store#14]
Hi all,

I'm curious why the `have_published_event` matcher only supports block expectations as stated in the readme. I'm curious to know the reason why we wouldn't be able to do `expect(...).to have_published_event(SomeEventClass)`

Thank you!

**Comment by palkan** [comment]
Hey!

Enforcing block expectations prevent from potential flakiness caused by shared state (or setup code which may also trigger events).
