### ISSUE TITLE
Fix upstream RES compatibility

### ISSUE THREAD

**Issue by palkan** [palkan/active_event_store#3]
Looks like events serialization internals are going to change in the future RES releases (for example, https://github.com/RailsEventStore/rails_event_store/pull/760).

Currently, our edge builds are broken: https://github.com/palkan/active_event_store/runs/1148181711

**Comment by palkan** [comment]
Hey @pawelpacana! When do you plan to release the new version with the above mentioned changes?

Is there a changelog/upgrade notes somewhere, so we can prepare for the upgrade?

**Comment by pawelpacana** [comment]
Hey!

There will be a changelog and the release would with breaking changes will be released as 2.0. I haven't looked into it yet in detail but we'll most likely release 1.99 with deprecation notices and backward compatibility if possible.

I'll keep you posted

**Comment by palkan** [comment]
@pawelpacana Thank you!

**Comment by pawelpacana** [comment]
No 1.99 release. Deprecations messages where possible in 2.0 release but it still requires changes in a database structure. Please have a look at https://github.com/RailsEventStore/rails_event_store/issues/791 for changelogs.

**Comment by apauly** [comment]
Hey @palkan!
As expected, newer version of RES will cause an exception (`missing keyword: :serializer`). It seems the latest supported version is 1.3.1  (I cannot find a 1.99).

Is this still actively maintained? 
If so, I'd consider creating a PR to support newer RES versions as well :)

**Comment by palkan** [comment]
> Is this still actively maintained?

Kind of: we're still using this gem in some projects but me personally not involved.

>  I'd consider creating a PR to support newer RES versions as well :)

That would be awesome!

**Comment by pawelpacana** [comment]
@apauly  If you have any questions regarding RES on this, feel free to ping me here or drop in on our [discord](https://discord.gg/qjPr9ZBpX6) or [forum](https://github.com/RailsEventStore/rails_event_store/discussions) :wave:
